frames/urls.py
from django.urls import path
from frames import views


app_name = "frames"
urlpatterns = [
    path("", views.FramesListView.as_view(), name="frame_list"),
    path("like/", views.frame_like_toggle, name="frame_like"),
    path("vote/", views.frame_vote_toggle, name="frame_vote"),
]

phlossineyewear/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from phlossineyewear.views import HomeView
from frames import urls as frames_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", HomeView.as_view(), name="home"),
    path("frames/", include(frames_urls, namespace="frames")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frames/models.py
from django.db import models
from django.conf import settings


class FrameDesign(models.Model):
    image = models.ImageField()
    sku = models.CharField(max_length=20)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    premium_votes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="premium_votes")
    variation = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f"SKU {self.sku}-{self.variation:0>2}"

    class Meta:
        ordering = ["sku", "variation"]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

frames/views.py
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import generic
from frames import models


class FramesListView(LoginRequiredMixin, generic.ListView):
    template_name = "frames/frames_list.html"
    model = models.FrameDesign
    paginate_by = 36
    paginate_orphans = 4

    def get_ordering(self):
        if order := self.request.GET.get("order"):
            return order
        return ["sku", "variation"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liked_frames"] = models.FrameDesign.objects.filter(likes__in=[self.request.user])
        context["voted_frames"] = models.FrameDesign.objects.filter(premium_votes__in=[self.request.user])
        return context


def frame_like_toggle(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            frames_id = data.get("frames_id")
            frames = models.FrameDesign.objects.get(id=frames_id)
            if request.user in frames.likes.all():
                frames.likes.remove(request.user)
                action = "removed from"
            else:
                frames.likes.add(request.user)
                action = "added to"
            frames.save()
            return JsonResponse({"status": f"Frames {action} likes"})
        except Exception as e:
            return JsonResponse({"status": f"error: {e}"}, status=400)


def frame_vote_toggle(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            frames_id = data.get("frames_id")
            frames = models.FrameDesign.objects.get(id=frames_id)
            if request.user in frames.premium_votes.all():
                frames.premium_votes.remove(request.user)
                action = "removed from"
            else:
                frames.premium_votes.add(request.user)
                action = "added to"
            frames.save()
            return JsonResponse({"status": f"Frames {action} premium votes"})
        except Exception as e:
            return JsonResponse({"status": f"error: {e}"}, status=400)

phlossineyewear/views.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = "home.html"

users/views.py
from django.shortcuts import render

# Create your views here.

frames/templates/frames/frames_list.html
{% extends "base.html" %}


{% block title %}Frames | {% endblock %}


{% block content %}
<v-container>
  <v-row>
    <v-col cols="12" md="8">
      <h2 class="text-h2 d-inline-block mr-3">Frames |</h2>
      <h4 class="text-h4 d-inline-block">Select the frames you like</h4>
    </v-col>
    <v-col cols="12" md="4">
      <v-select
          outlined
          :items="orderItems"
          label="Order by"
          @change="updateOrdering"
          v-model="order"
      ></v-select>
    </v-col>
  </v-row>

  <v-row class="mt-6">
    <v-col cols="12" sm="6" md="4" lg="3" v-for="frame in frames">
      <v-card>
        <v-card-text>
          <v-row no-gutters>
            <v-col cols="12">
              <v-dialog width="90vw">
                <template v-slot:activator="{ on, attrs }">
                  <v-img :src="frame.url" v-on="on" v-bind="attrs"></v-img>
                </template>
                <v-card max-width="90vw">
                  <v-img :src="frame.url" contain max-height="100%"></v-img>
                </v-card>
              </v-dialog>
            </v-col>
            <v-col cols="12" lg="6">
              <div class="d-flex align-center">
                <v-btn icon color="red" @click="toggleLike(frame)" x-large>
                  <v-icon>[[ frame.liked ? 'mdi-heart' : 'mdi-heart-outline' ]]</v-icon>
                </v-btn>
                <span class="text-h5 my-auto">[[ frame.likes|localeString ]]</span>
              </div>
            </v-col>
            <v-col cols="12" lg="6">
              <div class="d-flex align-center">
                <v-btn icon color="orange" @click="toggleVote(frame)" x-large>
                  <v-icon>[[ frame.voted ? 'mdi-star' : 'mdi-star-outline' ]]</v-icon>
                </v-btn>
                <span class="text-h5">[[ frame.premiumVotes|localeString ]]</span>
              </div>
            </v-col>
          </v-row>
        </v-card-text>
      </v-card>
    </v-col>
  </v-row>

  <v-pagination
      v-model="page"
      :length="pageCount"
      :total-visible="10"
      class="my-2"
      @input="changePage"
  ></v-pagination>

</v-container>
{% endblock %}


{% block data %}
  frames: [
    {% for frame in object_list %}
    {
      id: {{ frame.id }},
      url: '{{ frame.image.url }}',
      sku: '{{ frame.sku }}',
      variation: '{{ frame.variation|stringformat:"02d" }}',
      likes: {{ frame.likes.count }},
      liked: {% if frame in liked_frames %}true{% else %}false{% endif %},
      premiumVotes: {{ frame.premium_votes.count }},
      voted: {% if frame in voted_frames %}true{% else %}false{% endif %},
      likedFrames: "{{ liked_frames }}",
      frame: "{{ frame }}"
    }{% if not forloop.last %},{% endif %}
    {% endfor %}
  ],
  page: {{ page_obj.number }},
  pageCount: {{ paginator.num_pages }},
  orderItems: [
    {text: "Default", value: null},
    {text: "Likes", value: "-likes"},
    {text: "Likes (ascending)", value: "likes"},
    {text: "Premium votes", value: "-premium_votes"},
    {text: "Premium votes (ascending)", value: "premium_votes"}
  ],
  order: {% if request.GET.order %}"{{ request.GET.order }}"{% else %}null{% endif %},
{% endblock %}


{% block methods %}
{
  toggleLike(obj) {
    this.$http.post("{% url "frames:frame_like" %}", {"frames_id": obj.id})
      .then(r => r.json())
      .then(r => {
        console.log(r)
        this.$snotify.success(r["status"], "Success")
        if(r["status"] == "Frames added to likes") {
          obj.liked = true
          obj.likes++
        } else {
          obj.liked = false
          obj.likes--
        }
      })
      .catch(err => {
        console.log(err)
        err = err.json()
        this.$snotify.error(err["status"], "Error")
      })
  },
  toggleVote(obj) {
    this.$http.post("{% url "frames:frame_vote" %}", {"frames_id": obj.id})
      .then(r => r.json())
      .then(r => {
        console.log(r)
        this.$snotify.success(r["status"], "Success")
        if(r["status"] == "Frames added to premium votes") {
          obj.voted = true
          obj.premiumVotes++
        } else {
          obj.voted = false
          obj.premiumVotes--
        }
      })
      .catch(err => {
        console.log(err)
        err = err.json()
        this.$snotify.error(err["status"], "Error")
      })
  },
  changePage(newPage) {
    let params = new URLSearchParams(window.location.search)
    params.set('page', newPage)
    window.location = '{% url "frames:frame_list" %}?' + params.toString()
  },
  updateOrdering(selected) {
    if (selected) {
      window.location = `{% url "frames:frame_list" %}?order=${selected}`
    } else {
      window.location = "{% url "frames:frame_list" %}"
    }
  }
}
{% endblock %}


{% block filters %}
{
  localeString: function (value) {
    return value.toLocaleString("en-US");
  }
}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
  <title>{% block title %}{% endblock title %}Phlossin Eyewear</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vuetify@2/dist/vuetify.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vue-snotify@3.2.1/styles/material.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'img/icon-color.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'img/icon-color.ico' %}" type="image/x-icon">
  {% block additional_css %}{% endblock %}
  {% block meta %}{% endblock %}
</head>
<body>
  <v-app id="app" v-cloak>
    {% include "navbar.html" %}
    {% include "sidebar.html" %}

    <v-main>
      {% block content %}{% endblock %}
      <vue-snotify></vue-snotify>
    </v-main>

    {% include "footer.html" %}
  </v-app>
  <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2/dist/vuetify.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-resource@1/dist/vue-resource.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-snotify@3/vue-snotify.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  {% block additional_vue_scripts %}{% endblock %}

  <script>
    const None = null;
    const False = false;
    const True = true;
    const csrf_token = Cookies.get('csrftoken');
    {% block vue_use %}{% endblock %}
    Vue.http.interceptors.push((request, next) => {
      request.headers.set("X-CSRFToken", csrf_token)
      next()
    })
    const app = new Vue({
      delimiters: ['[[', ']]'],
      el: '#app',
      vuetify: new Vuetify(),
      data: {
        sidebar: null,
        activePage: '{{ request.path }}',
        pageName: '{{ request.resolver_match.url_name }}',
        {% block data %}{% endblock %}
      },
      props: {% block props %}{}{% endblock %},
      methods: {% block methods %}{}{% endblock %},
      watch: {% block watch %}{}{% endblock %},
      computed: {% block computed %}{}{% endblock %},
      mounted() {% block mounted %}{}{% endblock %},
      created() {% block created %}{}{% endblock %},
      filters: {% block filters %}{}{% endblock %}
    });
  </script>
  {% block additional_scripts %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<v-container>

  <v-img class="mx-auto my-12" max-height="100vh" contain src="{% static 'img/color1_logo_transparent_background.png' %}"></v-img>
  
</v-container>
{% endblock %}

templates/navbar.html
{% load static %}

<v-app-bar app dark>
  <v-app-bar-nav-icon @click="sidebar = !sidebar" class="d-md-none"></v-app-bar-nav-icon>
  <v-toolbar-title>
    <a href="/">
      <img src="{% static "img/logo-white.png" %}" height="32px" class="my-auto">
    </a>
  </v-toolbar-title>
  <v-spacer></v-spacer>
  <v-toolbar-items>
    <v-btn text href="{% url "frames:frame_list" %}">Frames</v-btn>
    {% if user.is_authenticated %}
      <v-btn text href="{% url "account_logout" %}" color="error">Log out</v-btn>
    {% else %}
      <v-btn text href="{% url "account_login" %}" color="success">Login</v-btn>
      <v-btn text href="{% url "account_signup" %}" color="info">Sign up</v-btn>
    {% endif %}
  </v-toolbar-items>
</v-app-bar>